// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import { Test } from "forge-std/Test.sol";
import { PoseidonT2 } from "protocol-solidity/hashers/Poseidon.sol";

/// @notice Installs the REAL PoseidonT2 library bytecode at the address forge links
///         the library to in tests.
/// @dev Forge auto-deploys external libraries referenced by test contracts via CREATE2
///      from the default create2 deployer (0x4e59b4...) with salt 0 — but it deploys the
///      repo's Poseidon.sol STUB (empty function bodies), which returns nothing.
///      Production deploys link to circomlibjs-generated bytecode instead. Tests etch
///      that same real runtime code (test/fixtures/PoseidonT2.json, produced by
///      circomlibjs poseidon_gencontract.createCode(1) — the generator
///      scripts/deploy-poseidon.mjs uses for live deployments) over the linked stub
///      address, so on-chain slash verification runs the identical Poseidon
///      implementation as mainnet. The linked address is recomputed from
///      type(PoseidonT2).creationCode so it tracks compiler/profile changes.
abstract contract PoseidonT2Fixture is Test {
    /// forge default CREATE2 deployer used for test library linking
    address internal constant CREATE2_DEPLOYER = 0x4e59b44847b379578588920cA78FbF26c0B4956C;

    /// The address forge linked PoseidonT2 to (stub code etched over in constructor).
    address internal immutable poseidonT2;

    constructor() {
        poseidonT2 = address(
            uint160(
                uint256(
                    keccak256(
                        abi.encodePacked(
                            bytes1(0xff), CREATE2_DEPLOYER, bytes32(0), keccak256(type(PoseidonT2).creationCode)
                        )
                    )
                )
            )
        );
        address deployed = vm.deployCode("test/fixtures/PoseidonT2.json");
        vm.etch(poseidonT2, deployed.code);
    }

    /// @dev PoseidonT2(secret) as bytes32 — the on-chain identity commitment scheme.
    function _poseidonT2(uint256 secret) internal pure returns (bytes32) {
        uint256[1] memory input;
        input[0] = secret;
        return bytes32(PoseidonT2.poseidon(input));
    }
}
